### ISSUE TITLE
WatchOS App Store Publishing Question (bitcode)

### ISSUE THREAD

**Issue by cuberob** [magnatronus/flutter-watchtips#1]
Hi There,

Thanks for sharing this project :). I'm in the process of rewriting one of my apps to Flutter and also want to add a WatchOS app but after some searching I discovered that WatchOS requires bitcode support to publish it and I stumbled upon this issue which states bitcode is not yet supported: https://github.com/flutter/flutter/issues/15288 
Did you manage to publish the app even without bitcode or am I missing something obvious?

Thanks!

**Comment by magnatronus** [comment]
The issue (I think) with bitcode support is that currently a WatchOS app cannot be written using Flutter. What I have done is add a WatchOS extension to a flutter app with the WatchOS app written using XCode.

I have not tried since I did the original submission but had no problems when I did it. The only issues were actually building the Flutter project which hopefully I documented in the readme.

**Comment by cuberob** [comment]
Ah that's great news, thanks for the heads up. I've been running into some dependency issues when trying to add a WatchOS target (similar to someone you helped out here: https://github.com/flutter/flutter/issues/29531) but hopefully I can work around that and get up and running as well then. Consider this "issue" closed then :).
